<?php

namespace Qd\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BatailleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BatailleRepository extends EntityRepository
{
}
