<?php

namespace Qd\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * OpendataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpendataRepository extends EntityRepository
{
    public function myFindByAll()
    {
        //$queryBuilder = $this->createQueryBuilder('a');
        $queryBuilder = $this->_em->createQueryBuilder()
            ->select('o.pays', 'o.reg', 'o.edif', 'o.leg', 'o.obj', 'o.lieucor', 'o.autp', 'o.serie')
            ->from($this->_entityName, 'o');

        $query = $queryBuilder->getQuery();
        $resultats = $query->getResult();

        return $resultats;
    }

    public function myFindData($madate){
        $query = $this->_em->createQuery(
            'SELECT c.videov, c.videop, c.adresse, c.leg
            FROM QdBlogBundle:Opendata c
            WHERE c.datepv = ?1');
        $query->setParameter(1, $madate);

        $resultats = $query->getResult();

        return $resultats;
    }

    public function myFindByReq($cat, $req)
    {
        $query = $this->_em->createQuery(
           'SELECT c.videov, c.videop, c.leg FROM QdBlogBundle:Opendata c WHERE c.'.$cat .'= ?2');
        //$query->setParameters(array(1 => 'c.'.$cat, 2 => $req));
        $query->setParameter(2 , $req);

        //$query = $queryBuilder->getQuery();
        $resultats = $query->getResult();

        return $resultats;
    }

    public function myDistinctPays()
    {
        //$queryBuilder = $this->createQueryBuilder('a');
        $query = $this->_em->createQuery(
            'SELECT DISTINCT(c.pays) as title FROM QdBlogBundle:Opendata c  ORDER BY c.pays ASC');

        //$query = $queryBuilder->getQuery();
        $resultats = $query->getResult();

        return $resultats;
    }
    public function myDistinctRegion()
    {
        //$queryBuilder = $this->createQueryBuilder('a');
        $query = $this->_em->createQuery(
            'SELECT DISTINCT(c.reg) as title FROM QdBlogBundle:Opendata c  ORDER BY c.reg ASC');

        //$query = $queryBuilder->getQuery();
        $resultats = $query->getResult();

        return $resultats;
    }
    public function myDistinctDpt()
    {
        //$queryBuilder = $this->createQueryBuilder('a');
        $query = $this->_em->createQuery(
            'SELECT DISTINCT(c.dpt) as title FROM QdBlogBundle:Opendata c  ORDER BY c.dpt ASC');

        //$query = $queryBuilder->getQuery();
        $resultats = $query->getResult();

        return $resultats;
    }
    public function myDistinctCom()
    {
        //$queryBuilder = $this->createQueryBuilder('a');
        $query = $this->_em->createQuery(
            'SELECT DISTINCT(c.com) as title FROM QdBlogBundle:Opendata c ORDER BY c.com ASC ');

        //$query = $queryBuilder->getQuery();
        $resultats = $query->getResult();

        return $resultats;
    }
    public function myDistinctLeg()
    {
        //$queryBuilder = $this->createQueryBuilder('a');
        $query = $this->_em->createQuery(
            'SELECT DISTINCT(c.leg) as title FROM QdBlogBundle:Opendata c ORDER BY c.leg ASC ');

        //$query = $queryBuilder->getQuery();
        $resultats = $query->getResult();

        return $resultats;
    }
    public function myDistinctAutp()
    {
        //$queryBuilder = $this->createQueryBuilder('a');
        $query = $this->_em->createQuery(
            'SELECT DISTINCT(c.autp) as title FROM QdBlogBundle:Opendata c ORDER BY c.autp ASC');

        //$query = $queryBuilder->getQuery();
        $resultats = $query->getResult();

        return $resultats;
    }
    public function myDistinctAutoeu()
    {
        //$queryBuilder = $this->createQueryBuilder('a');
        $query = $this->_em->createQuery(
            'SELECT DISTINCT(c.autoeu) as title FROM QdBlogBundle:Opendata c  ORDER BY c.autoeu ASC');

        //$query = $queryBuilder->getQuery();
        $resultats = $query->getResult();

        return $resultats;
    }
    public function myDistinctSerie()
    {
        //$queryBuilder = $this->createQueryBuilder('a');
        $query = $this->_em->createQuery(
            'SELECT DISTINCT(c.serie) as title FROM QdBlogBundle:Opendata c  ORDER BY c.serie ASC');

        //$query = $queryBuilder->getQuery();
        $resultats = $query->getResult();

        return $resultats;
    }
}
